name: Upload to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::863362167483:role/github-actions-fileupload-to-s3
          aws-region: ap-northeast-1
      - name: Sync to S3
        run: |
          aws s3 sync . s3:// --delete